---
name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
      - uses: chartboost/ruff-action@v1
  build:
    needs: linting
    runs-on: ubuntu-latest
    timeout-minutes: 3
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.5.1
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: Install dependencies
        run: poetry install --no-interaction --no-root
      - name: Install library
        run: poetry install --no-interaction
      - name: Test
        env:
          GINGER_IT_API_KEY: ${{ secrets.GINGER_IT_API_KEY }}
        run: poetry run pytest tests
      - name: Generate coverage report
        env:
          GINGER_IT_API_KEY: ${{ secrets.GINGER_IT_API_KEY }}
        run: poetry run coverage run -m pytest --cov=gingerit --cov-report=xml tests
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          env_vars: OS,PYTHON
          files: ./coverage.xml
          fail_ci_if_error: true
          name: codecov-umbrella
          verbose: true
